//
// Copyright 2022 Z5Labs and Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: services/ingest/proto/service.proto

package proto

import (
	subgraph "github.com/z5labs/megamind/subgraph"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_ingest_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_ingest_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_services_ingest_proto_service_proto_rawDescGZIP(), []int{0}
}

var File_services_ingest_proto_service_proto protoreflect.FileDescriptor

var file_services_ingest_proto_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x73, 0x75,
	0x62, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2f, 0x73, 0x75, 0x62, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x84, 0x01, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x49, 0x6e,
	0x67, 0x65, 0x73, 0x74, 0x53, 0x75, 0x62, 0x67, 0x72, 0x61, 0x70, 0x68, 0x12, 0x12, 0x2e, 0x73,
	0x75, 0x62, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x53, 0x75, 0x62, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x49, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x2e, 0x73, 0x75, 0x62, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x53, 0x75, 0x62,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e,
	0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x32,
	0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x35, 0x6c,
	0x61, 0x62, 0x73, 0x2f, 0x6d, 0x65, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x64, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_ingest_proto_service_proto_rawDescOnce sync.Once
	file_services_ingest_proto_service_proto_rawDescData = file_services_ingest_proto_service_proto_rawDesc
)

func file_services_ingest_proto_service_proto_rawDescGZIP() []byte {
	file_services_ingest_proto_service_proto_rawDescOnce.Do(func() {
		file_services_ingest_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_ingest_proto_service_proto_rawDescData)
	})
	return file_services_ingest_proto_service_proto_rawDescData
}

var file_services_ingest_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_services_ingest_proto_service_proto_goTypes = []interface{}{
	(*IngestResponse)(nil),    // 0: proto.IngestResponse
	(*subgraph.Subgraph)(nil), // 1: subgraph.Subgraph
}
var file_services_ingest_proto_service_proto_depIdxs = []int32{
	1, // 0: proto.SubgraphIngest.IngestSubgraph:input_type -> subgraph.Subgraph
	1, // 1: proto.SubgraphIngest.Ingest:input_type -> subgraph.Subgraph
	0, // 2: proto.SubgraphIngest.IngestSubgraph:output_type -> proto.IngestResponse
	0, // 3: proto.SubgraphIngest.Ingest:output_type -> proto.IngestResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_ingest_proto_service_proto_init() }
func file_services_ingest_proto_service_proto_init() {
	if File_services_ingest_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_ingest_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IngestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_ingest_proto_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_ingest_proto_service_proto_goTypes,
		DependencyIndexes: file_services_ingest_proto_service_proto_depIdxs,
		MessageInfos:      file_services_ingest_proto_service_proto_msgTypes,
	}.Build()
	File_services_ingest_proto_service_proto = out.File
	file_services_ingest_proto_service_proto_rawDesc = nil
	file_services_ingest_proto_service_proto_goTypes = nil
	file_services_ingest_proto_service_proto_depIdxs = nil
}
